### ISSUE TITLE
Help with deserialization from JSON

### ISSUE THREAD

**Issue by nishal** [RestExpress/HyperExpress#2]
Great to see this on http://gradleplease.appspot.com/ :).

I'm new to HAL, so not sure how I would use HyperExpress to deserialize from JSON a domain object that included a _embedded key. I've pasted a partial section of my DTO and JSON. I'm using Jackson ObjectMapper to deserialize. Any quick pointers will be greatly appreciated, TIA.

My Domain Object:
    public class RecentActivityDTO extends AbstractDTO implements Serializable {
        private static final long serialVersionUID = 5697205059499896829L;

```
    private int perPageCount;
    private List<RecentActivityItemDTO> activities;
    // I'm using org.codehaus.jackson.map.ObjectMapper to deserialize from JSON to my DTO so not sure what this next line should look like, please help!
    // private HalResource _embedded; 

    // Getters and setters
}
```

JSON string returned from an API
{
    "perPageCount": 2,
    "activities": [ ... ],
    "_embedded": {
        "options": [
            {
                "title": "Since 24 Oct 2013",
                "_links": {
                    "self": {
                        "href": "/line/activities",
                    },
                "selected": true
                }
            },
            {
                "title": "Last 31 days",
                "_links": {
                    "self": {
                        "href": "/line/activities/?option=1"
                    }
                }
            },
            {
                "title": "Last 2 days",
                "_links": {
                    "self": {
                        "href": "/line/activities/?option=2"
                    }
                }
            }
        ]
    }

**Comment by evgeniy-tg** [comment]
Hello,
Can you provide some code, that describes how can I deserialize to a HalResource  and then navigate the _embedded rel.

I am trying to do it like this:
`HalResource hr = SerializationProvider.json().deserialize(responseString, HalResource.class);
List<Resource> hr1 = hr.getResources().get("datasourceassociations");`
But then I cannot extract my objects array from hr1, since hr1 is List of HalResources that somehow I need to cast them to my objects array.

Thanks,
